/*
 * Copyright 2002-2015 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.kerb4j.server.spring.webflux;

import com.kerb4j.common.util.Constants;
import com.kerb4j.server.spring.SpnegoRequestToken;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.security.authentication.AnonymousAuthenticationToken;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.authentication.ReactiveAuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.ReactiveSecurityContextHolder;
import org.springframework.security.core.context.SecurityContext;
import org.springframework.security.web.server.authentication.ServerAuthenticationConverter;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

import java.nio.charset.StandardCharsets;
import java.util.Base64;

/**
 * Reactive WebFlux authentication converter for SPNEGO authorization headers.
 * 
 * <p>Parses the SPNEGO authentication Header, which was generated by the browser
 * and creates a {@link SpnegoRequestToken} out of it. It will then
 * call the {@link ReactiveAuthenticationManager}.</p>
 *
 * <p>Basic authentication fallback is <strong>disabled</strong> by default. Enable it explicitly
 * via the constructor or {@link #setSupportBasicAuthentication(boolean)} if your use case
 * requires mixed Kerberos/password environments.</p>
 *
 * @author Mike Wiesner (original SpnegoAuthenticationProcessingFilter)
 * @author GitHub Copilot (WebFlux adaptation)
 * @since 1.0
 */
public class SpnegoServerAuthenticationConverter implements ServerAuthenticationConverter {

    private static final Log LOG = LogFactory.getLog(SpnegoServerAuthenticationConverter.class);

    private boolean supportBasicAuthentication = false;
    private boolean skipIfAlreadyAuthenticated = true;

    /**
     * Instantiates a new SPNEGO authentication converter.
     * Basic authentication fallback is disabled by default.
     */
    public SpnegoServerAuthenticationConverter() {
        this(false);
    }

    /**
     * Instantiates a new SPNEGO authentication converter with basic authentication support option.
     *
     * @param supportBasicAuthentication whether to support basic authentication fallback
     */
    public SpnegoServerAuthenticationConverter(boolean supportBasicAuthentication) {
        this.supportBasicAuthentication = supportBasicAuthentication;
    }

    @Override
    public Mono<Authentication> convert(ServerWebExchange exchange) {
        if (skipIfAlreadyAuthenticated) {
            return ReactiveSecurityContextHolder.getContext()
                    .map(SecurityContext::getAuthentication)
                    .filter(auth -> auth != null && auth.isAuthenticated() &&
                            !(auth instanceof AnonymousAuthenticationToken))
                    .flatMap(auth -> Mono.<Authentication>empty())
                    .switchIfEmpty(Mono.defer(() -> processAuthenticationHeader(exchange)));
        } else {
            return processAuthenticationHeader(exchange);
        }
    }

    private Mono<Authentication> processAuthenticationHeader(ServerWebExchange exchange) {
        String header = exchange.getRequest().getHeaders().getFirst(Constants.AUTHZ_HEADER);

        if (header == null) {
            return Mono.empty();
        }

        String negotiateToken = extractAuthenticationToken(header, Constants.NEGOTIATE_HEADER);
        if (negotiateToken != null) {
            if (LOG.isDebugEnabled()) {
                LOG.debug("Received Negotiate Authorization header for request " + exchange.getRequest().getURI());
            }

            String base64Token = negotiateToken.trim();
            if (base64Token.isEmpty()) {
                return Mono.empty();
            }
            byte[] kerberosTicket;
            try {
                kerberosTicket = Base64.getDecoder().decode(base64Token);
            } catch (IllegalArgumentException e) {
                return Mono.error(new BadCredentialsException("Failed to decode Negotiate token", e));
            }
            return Mono.just(new SpnegoRequestToken(kerberosTicket));

        }

        String basicToken = extractAuthenticationToken(header, Constants.BASIC_HEADER);
        if (supportBasicAuthentication && basicToken != null) {
            if (LOG.isDebugEnabled()) {
                LOG.debug("Received Basic Authorization header for request " + exchange.getRequest().getURI());
            }

            String token;
            try {
                token = new String(Base64.getDecoder().decode(basicToken), StandardCharsets.UTF_8);
            } catch (IllegalArgumentException e) {
                return Mono.error(new BadCredentialsException("Failed to decode Basic authentication token", e));
            }

            int delimiter = token.indexOf(":");
            if (delimiter == -1) {
                return Mono.error(new BadCredentialsException("Invalid Basic authentication token"));
            }

            String username = token.substring(0, delimiter);
            String password = token.substring(delimiter + 1);
            return Mono.just(new UsernamePasswordAuthenticationToken(username, password));
        }

        return Mono.empty();
    }

    private String extractAuthenticationToken(String header, String scheme) {
        if (header.length() <= scheme.length()) {
            return null;
        }
        if (!header.regionMatches(true, 0, scheme, 0, scheme.length())) {
            return null;
        }
        if (!Character.isWhitespace(header.charAt(scheme.length()))) {
            return null;
        }
        return header.substring(scheme.length()).trim();
    }

    /**
     * Sets whether to support basic authentication as fallback.
     * Defaults to {@code false}; set to {@code true} only when mixed
     * Kerberos/password environments require it.
     *
     * @param supportBasicAuthentication whether to support basic authentication
     */
    public void setSupportBasicAuthentication(boolean supportBasicAuthentication) {
        this.supportBasicAuthentication = supportBasicAuthentication;
    }

    /**
     * Sets whether to skip authentication if already authenticated.
     *
     * @param skipIfAlreadyAuthenticated whether to skip if already authenticated
     */
    public void setSkipIfAlreadyAuthenticated(boolean skipIfAlreadyAuthenticated) {
        this.skipIfAlreadyAuthenticated = skipIfAlreadyAuthenticated;
    }
}
